
# subject: 'cat:cs.*'
subject: 'cat:cs.* OR cat:q-fin.*'

keywords:
        parallel: 3
        language: 2
        distributed: 3
        database: 2
        crypt: 2
        identity management: 3
        authorization: 3
        authentication: 3
        simulation: 3
        emulation: 3
        analysis: 3
        marcket: 2
        trader: 3
        robot: 2
        operating system: 3
        ros2: 2

score_threshold: 0
